# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "nAvyjKgkn5G7BYXq85kNXBgb3fdzVSVibvaJKWftimjhHjKzjNfcoUk/IvuoEmwpP6TofgVRx2T689DaUqW29TVXV5O23DvOyJE6SpO7xn0yPC12SPPy3nwwCWkGYvy77akz3N+DvIwGZ712lF2gttTB/mjNB1ZcX5438nCDI1hUw5TcH2QoajhxGJVDJoHQBUxWcOLQh+N+6+ZGnenR7wfLcYOmC6dLNSS9Mn2f/IPF3y3xmq3HZ7CJpHJcfIQ1a0bnHa2h7CIMRZZeXzK/W2RD1qaZ2upz33lVgpCq+/pJCED3vk+XZgmATJML8vzRsY1FlgXgEfWYmaJlsUEcNb/Llu4hwmA9pFO0pI432S3z4pX7NlcVy8Om0eaYvMbyWX4VTOz1urutWTNHQ5337wbkaPYk5ELoI7Ph2pe0uvtlrHzCO6sQWjg79asyFj2zxefOWxRM4d8k1eRQoUZaRpq95wBVYbVCiZqMc+V7TrABBlfC7f8iDmTA4nLmH6f8RIHFL018ikgd6CaRbpSO2XSSNmktR7fuLmC68vBZ64CCxVGMn0poNbdHZVphQ3KgiKH2c2Qb990XgwV/YYDNrjgh2qwpB+NzhE3PJIYWs1AGyEU9fJRJV2ElfLeel9vAWqWSZ/7q+0yPb6ScVCQ4SOJ1TYUpb8qOV3VqgbN/BwQ="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      all_branches: true
